layout_spectrum: 0.519512220887412
typography_spectrum: 0.9976973188603943
color:
  brandStrength: 0.1589934918854275
  lightness: 0.4196948510750501
  saturation: 0.5812159191860383
  rhythmicContrast: 0.28807152892057186
  brandColors:
    - '#0B0C0E'
    - '#FCF9EA'
    - '#F7B846'
    - '#7D8B68'
    - '#EA7B34'
colors:
  brandColors:
    - 'hsl(0,0%,100%)'
    - 'hsl(0,0%,80%)'
    - 'hsl(0,0%,60%)'
    - 'hsl(0,0%,30%)'
    - 'hsl(0,0%,20%)'
name: AGROTEINA
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: video
    html: >-
      <iframe
      src="https://cdn.embedly.com/widgets/media.html?src=https%3A%2F%2Fwww.youtube.com%2Fembed%2FKQZUOZSOUD8%3Ffeature%3Doembed&url=http%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3DKQZUOZSOUD8&image=https%3A%2F%2Fi.ytimg.com%2Fvi%2FKQZUOZSOUD8%2Fhqdefault.jpg&key=a715cf41cc93453ca338d350cd26f87b&type=text%2Fhtml&schema=youtube"
      width="640" height="360" scrolling="no" frameborder="0"
      allowfullscreen></iframe>
    src: !<tag:yaml.org,2002:js/undefined> ''
    metadata:
      author:
        - name: Suzzette Tamez
          url: 'https://www.youtube.com/channel/UCOTvu-mIEaHZrBKO_jYU2mA'
          avatar: {}
      related: []
      publisher:
        url: 'https://www.youtube.com/'
        name: YouTube
        favicon: 'https://s.ytimg.com/yts/img/favicon-vflz7uhzw.ico'
        domain: www.youtube.com
      keywords:
        - '#insectos'
        - '#insectoscomoalimento'
        - '#alimentoparagranjas'
        - '#productorainsectos'
        - '#empresasverdesyucatecas'
        - '#granjasdeinsectos'
        - '#tilapia'
        - '#alimentoparaanimales'
        - '#...'
      description: >-
        Éste video muestra el crecimiento del gusano de la harina a pequeña
        escala en el laboratorio de la Incubadora de Alto Impacto del Parque
        Tecnia. En AGROTEINA desarrollamos un sistema de producción sustentable
        usando productos secundarios de bajo valor provenientes de la industria
        cervecera y la agrícola.
      '@type': VideoObject
      app_links:
        - url: 'vnd.youtube://www.youtube.com/watch?v=KQZUOZSOUD8&feature=applinks'
          type: ios
          namespace: ai
          app_store_id: '544007664'
          app_name: YouTube
        - url: 'vnd.youtube://www.youtube.com/watch?v=KQZUOZSOUD8&feature=applinks'
          type: android
          namespace: ai
          app_name: YouTube
          package: com.google.android.youtube
        - url: 'https://www.youtube.com/watch?v=KQZUOZSOUD8&feature=applinks'
          type: web
          namespace: ai
        - url: 'vnd.youtube://www.youtube.com/watch?v=KQZUOZSOUD8&feature=applinks'
          namespace: twitter
          type: ipad
          name: YouTube
          id: '544007664'
        - url: 'vnd.youtube://www.youtube.com/watch?v=KQZUOZSOUD8&feature=applinks'
          namespace: twitter
          type: iphone
          name: YouTube
          id: '544007664'
        - url: 'https://www.youtube.com/watch?v=KQZUOZSOUD8'
          namespace: twitter
          type: googleplay
          name: YouTube
          id: com.google.android.youtube
        - path: http/www.youtube.com/watch?v=KQZUOZSOUD8
          package: com.google.android.youtube
          namespace: google
          type: android
        - path: vnd.youtube/www.youtube.com/watch?v=KQZUOZSOUD8
          package: '544007664'
          namespace: google
          type: ios
      '@context': 'http://schema.org'
      isBasedOnUrl: 'https://www.youtube.com/watch?v=KQZUOZSOUD8'
      title: 'AGROTEINA: Alimento de alta calidad proteica.'
      datePublished: null
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
title: 'Proteina sustentable, natural y local'
description: Alimento de alta calidad proteica a base de insectos
logo: null
author:
  name: >-
    SUSTAINABLE FEED SOLUTIONS S.A.P.I. de C.V. Todos los derechos reservados.
    AGROTEINA es una marca registrada
  email: scubasuset@gmail.com
  url: 'https://about.me/Suxz'
purpose:
  - type: external
    url: 'https://scubasuset.clickfunnels.com/optin'
    label: '¿Notificaciones? Sí, ¡gracias!'
  - type: internal
    label: Productos
    item: 2209aa07-d1d1-4d97-9e2d-f8cde678e795
github: true
url: 'https://www.agroteina.com'
