layout_spectrum: 0.519512220887412
typography_spectrum: 0.9976973188603943
color:
  brandStrength: 0.1589934918854275
  lightness: 0.4196948510750501
  saturation: 0.5812159191860383
  rhythmicContrast: 0.28807152892057186
  brandColors:
    - '#0B0C0E'
    - '#FCF9EA'
    - '#F7B846'
    - '#7D8B68'
    - '#EA7B34'
colors:
  brandColors:
    - 'hsl(0,0%,100%)'
    - 'hsl(0,0%,80%)'
    - 'hsl(0,0%,60%)'
    - 'hsl(0,0%,30%)'
    - 'hsl(0,0%,20%)'
name: SUSTAINABLE FEED SOLUTIONS
content: []
title: 'Proteina sustentable, natural y local'
description: ' Somos la primer empresa en México que produce proteína a base de insectos. Ofrecemos un producto de alta calidad, sustentable y local que genera valor ambiental y social. '
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/09facbd1-ec7b-494c-be2e-7545ea4526ce.png
author:
  name: SUZZETTE TAMEZ CRUZ
  email: scubasuset@gmail.com
  url: 'https://about.me/Suxz'
purpose:
  - type: external
    url: 'https://scubasuset.clickfunnels.com/optin'
    label: Haz click aquí para saber más
github: true
