layout_spectrum: 0.9204429001508668
typography_spectrum: 0.62704243689047
color:
  brandStrength: 0.42749024981632827
  lightness: 0.8121161610735489
  saturation: 0.7704069909135267
  rhythmicContrast: 0.09245639529438818
  brandColors:
    - '#354242'
    - '#ACEBAE'
    - '#FFFF9D'
    - '#C9DE55'
    - '#7D9100'
colors:
  brandColors:
    - 'hsl(0,0%,100%)'
    - 'hsl(0,0%,80%)'
    - 'hsl(0,0%,60%)'
    - 'hsl(0,0%,30%)'
    - 'hsl(0,0%,20%)'
name: AGROTEINA
content: []
title: ' '
description: ' '
logo: null
author:
  name: >-
    SUSTAINABLE FEED SOLUTIONS S.A.P.I. de C.V. Todos los derechos reservados.
    AGROTEINA es una marca registrada
  email: scubasuset@gmail.com
  url: 'https://about.me/Suxz'
purpose:
  - type: external
    url: 'https://scubasuset.clickfunnels.com/optin'
    label: '¿Notificaciones? Sí, ¡gracias!'
  - type: internal
    label: Productos
    item: 2209aa07-d1d1-4d97-9e2d-f8cde678e795
github: true
url: 'https://www.agroteina.com'
