colors:
  brandColors:
    - 'hsl(0,0%,100%)'
    - 'hsl(0,0%,80%)'
    - 'hsl(0,0%,60%)'
    - 'hsl(0,0%,30%)'
    - 'hsl(0,0%,20%)'
name: SUSTAINABLE FEED SOLUTIONS
layout_spectrum: 0.6680565057322383
typography_spectrum: 0.8666098124813288
color:
  brandStrength: 0.12000857037492096
  lightness: 0.7503885955084115
  saturation: 0.4109168143477291
  rhythmicContrast: 0.8043191095348448
  brandColors:
    - '#D8CAA8'
    - '#5C832F'
    - '#284907'
    - '#382513'
    - '#363942'
content: []
title: 'Proteina sustentable, natural y local'
description: ' Somos la primer empresa en México que produce proteína a base de insectos. Ofrecemos un producto de alta calidad, sustentable y local que genera valor ambiental y social. '
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/09facbd1-ec7b-494c-be2e-7545ea4526ce.png
author:
  name: SUZZETTE TAMEZ CRUZ
  email: scubasuset@gmail.com
  url: 'https://about.me/Suxz'
purpose:
  - type: phone
    url: 'tel:5219992988998'
    label: Talk to us
  - type: contact
    url: 'mailto:info.gaiatan@gmail.com'
    label: Contact us
github: true
