layout_spectrum: 0.9204429001508668
typography_spectrum: 0.62704243689047
color:
  brandStrength: 0.42749024981632827
  lightness: 0.8121161610735489
  saturation: 0.7704069909135267
  rhythmicContrast: 0.09245639529438818
  brandColors:
    - '#354242'
    - '#ACEBAE'
    - '#FFFF9D'
    - '#C9DE55'
    - '#7D9100'
colors:
  brandColors:
    - 'hsl(0,0%,100%)'
    - 'hsl(0,0%,80%)'
    - 'hsl(0,0%,60%)'
    - 'hsl(0,0%,30%)'
    - 'hsl(0,0%,20%)'
name: AGROTEINA
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/c09b2b33-a721-4797-897b-3a575b2e1108.jpg">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/c09b2b33-a721-4797-897b-3a575b2e1108.jpg
    metadata:
      author: []
      related: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      keywords: []
      description: ''
      inLanguage: !<tag:yaml.org,2002:js/undefined> ''
      app_links: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      datePublished: null
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
title: ' '
description: ' '
logo: null
author:
  name: >-
    SUSTAINABLE FEED SOLUTIONS S.A.P.I. de C.V. Todos los derechos reservados.
    AGROTEINA es una marca registrada
  email: scubasuset@gmail.com
  url: 'https://about.me/Suxz'
purpose:
  - type: external
    url: 'https://scubasuset.clickfunnels.com/optin'
    label: '¿Notificaciones? Sí, ¡gracias!'
  - type: internal
    label: Productos
    item: 2209aa07-d1d1-4d97-9e2d-f8cde678e795
github: true
url: 'https://www.agroteina.com'
